from django.urls import path
from django.views.generic import TemplateView
from contact_form.views import ContactFormView
from .forms import HospitalContactForm
from . import views 


#a list of the url's here which can be accessed via the views.
urlpatterns = [
    path('contact/', ContactFormView.as_view(form_class=HospitalContactForm), name='contact_form'),
    path('contact/sent/', TemplateView.as_view(template_name='contact_form/contact_form_sent.html'), name='contact_form_sent'),
    path('', views.index, name='index'),
    path('about/', views.about, name='about_this'),
    path('home-base/', views.home_base, name='home_base'),
    path('patient-home/<int:id>/', views.patient_home, name='patient_home'),
    path('staff-home/<int:id>/', views.staff_home, name='staff_home'),
    path('patient-details/<int:id>/', views.patient_details, name='patient_details'),
    path('patient-details/<int:id>/update/', views.patient_details_update, name='patient_details_update'),
    path('staff-details/<int:id>/', views.staff_details, name='staff_details' ),
    path('profile/<int:id>/create-event/', views.event_create, name='event_create' ),
    path('profile/<int:id>/events/<int:event_pk>/update-event/', views.EventUpdateView.as_view(), name='edit_event'),
    path('profile/<int:id>/events/<int:event_pk>/delete-event/', views.EventDeleteView.as_view(), name='delete_event'),
    path('profile/<int:id>/events/', views.events, name='events'),
    path('profile/<int:id>/search-result/', views.PatientSearchResultsView.as_view(), name='patient_search_results'),
    path('profile/<int:id>/create-task/', views.TaskCreateView.as_view(), name='create_task'),
    path('profile/<int:id>/task-home/', views.task_home, name='task'),
    path('task_complete/', views.task_complete, name='task_complete'),
    path('delete-task/<int:task_pk>', views.TaskDeleteView.as_view(), name='delete_task'),
    path('profile/<int:id>/tasks/<int:task_pk>/update-task/', views.TaskUpdateView.as_view(), name='edit_task'),
    path('profile/<int:id>/medication/', views.MedicationView, name='medication'),
    path('profile/<int:id>/add-medication/', views.MedicationCreateView.as_view(), name='create_medication'),
    path('medication-done/', views.medication_done, name='medication_done'),   
    path('profile/<int:id>/conditions/', views.ConditionsView, name='conditions'),
    path('profile/<int:id>/conditions/<int:condition_pk>/update-condition/', views.ConditionUpdateView.as_view(), name='edit_condition'),
    path('profile/<int:id>/add-condition/', views.ConditionCreateView.as_view(), name='create_condition'),
    path('profile/<int:id>/immunizations/', views.ImmunizationsView, name='immunizations'),
    path('profile/<int:id>/documents/', views.DocumentsView, name='documents'),
    path('profile/<int:id>/add-document/', views.DocumentCreateView.as_view(), name='create_document'),
    path('profile/<int:id>/pdf-view/<int:pdfid>/', views.pdf_view, name='pdf_view'),   
    path('delete-document/<int:document_pk>/', views.DocumentDeleteView.as_view(), name='delete_document'),
    path('profile/<int:id>/vitals/', views.vitalsview, name='vitals'),
    path('profile/<int:id>/groups/', views.autocompleteGroup, name='groups'),
    path('profile/<int:id>/doctors/', views.doctors_view, name='doctors_view'),
    path('profile/<int:id>/doctors/register/', views.doctors_reg, name='doctors_reg'),
    path('register-hospital/', views.register_hospital, name='register_hospital'),   
    path('accept-patient/', views.accept_patient, name='accept_patient'),
    path('reject-application/', views.reject_patient, name='reject_application'),
    path('profile/<int:id>/patients/', views.PatientView.as_view(), name='patient_list'),
    path('profile/<int:id>/hospital-details/', views.hospital_details, name='hospital_details'),
    path('profile/<int:id>/create-staff/', views.StaffCreateView, name='create_staff'),
    path('profile/<int:id>/staff/<int:pk>/delete-staff/', views.StaffDeleteView.as_view(), name='delete_staff'),
    path('profile/<int:id>/add-schedule/', views.add_schedule, name='add_schedule'),
    path('profile/<int:id>/shifts/<int:pk>/edit-shift/', views.ShiftUpdateView.as_view(), name='edit_shift'),
    path('profile/<int:id>/shifts/<int:pk>/delete-shift/', views.ShiftDeleteView.as_view(), name='delete_shift'),
    path('profile/<int:id>/patients/<int:pk>/', views.patient_view, name='patient_view'),
    path('profile/<int:id>/patients/<int:pk>/create-immunization/', views.ImmunizationCreateView, name='doc_create_immunization'),
    path('profile/<int:id>/patients/<int:pk>/create-condition/', views.DoctorConditionCreateView, name='doc_create_condition'),
    path('profile/<int:id>/patients/<int:pk>/create-medication/', views.DoctorMedicationCreateView, name='doc_create_medication'),
    path('profile/<int:id>/patients/<int:pk>/upload-document/', views.DoctorDocumentCreateView, name='doc_create_document'),
    path('profile/<int:id>/patients/<int:pk>/delete/', views.PatientHospitalDeleteView.as_view(), name='delete_relation'),
    path('profile/<int:id>/staff-create-event/', views.staff_event_create, name='staff_event_create'),
    path('profile/<int:id>/add_height/', views.HeightCreateView, name='add_height'),
    path('profile/<int:id>/add_weight/', views.WeightCreateView, name='add_weight'),
    path('profile/<int:id>/help/', views.help, name='help'),
    path('weightdata/<int:id>/', views.WeightData.as_view(), name='weight_data'),
]