# Generated by Django 2.2.3 on 2019-07-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=64)),
                ('line2', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(max_length=32)),
                ('postcode', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('postcode', 'line1')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('read', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(choices=[('DL', 'Discharge Letter'), ('LR', 'Lab Result')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myhealthdb.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('country', models.CharField(choices=[('UK', 'United Kingdom'), ('IRL', 'Ireland'), ('FR', 'France')], max_length=64)),
                ('type', models.CharField(choices=[('GP', 'General Practice'), ('GH', 'General Hospital'), ('SH', 'Specialized Hospital')], max_length=64)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myhealthdb.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('sex', models.BooleanField()),
                ('dob', models.DateField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('tel_no', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('security_qu', models.CharField(max_length=128)),
                ('security_ans', models.CharField(max_length=64)),
                ('nhs_no', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=32)),
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealthdb.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomsSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=256, null=True)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=32)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealthdb.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('security_qu', models.CharField(max_length=128)),
                ('security_ans', models.CharField(max_length=64)),
                ('tel_no', models.CharField(blank=True, max_length=32, null=True)),
                ('role', models.CharField(max_length=32)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myhealthdb.Ward')),
            ],
        ),
        migrations.CreateModel(
            name='PatientEm',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('emcontact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealthdb.EmergencyContact')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealthdb.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDoctor',
            fields=[
                ('primary', models.BooleanField()),
                ('pd_id', models.AutoField(primary_key=True, serialize=False)),
                ('inpatient', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealthdb.Staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealthdb.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('R', 'Run'), ('J', 'Jog'), ('W', 'Walk'), ('C', 'Cycle'), ('S', 'Swim')], max_length=32)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('distance_unit', models.CharField(blank=True, choices=[('m', 'Run'), ('Km', 'Jog'), ('Mi', 'Walk')], max_length=32, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhealthdb.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('deadline', models.DateTimeField(primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=256)),
                ('complete', models.BooleanField()),
                ('name', models.CharField(max_length=32)),
                ('completed_by', models.ForeignKey(default='default@default.com', on_delete=django.db.models.deletion.SET_DEFAULT, to='myhealthdb.Staff')),
            ],
            options={
                'unique_together': {('deadline', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(max_length=64)),
                ('amount', models.CharField(blank=True, max_length=16, null=True)),
                ('frequency', models.CharField(max_length=64)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealthdb.Patient')),
            ],
            options={
                'unique_together': {('type', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='Immunization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('FLU', 'Influenza'), ('ZIK', 'Zika Virus')], max_length=64)),
                ('amount', models.CharField(max_length=32)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealthdb.Patient')),
            ],
            options={
                'unique_together': {('type', 'patient', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('S', 'Surgery'), ('C', 'Consultation'), ('I', 'Immunization'), ('E', 'Emergency')], max_length=32)),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('letter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myhealthdb.Document')),
                ('pd_relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myhealthdb.PatientDoctor')),
            ],
            options={
                'unique_together': {('date_in', 'pd_relation')},
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('stop', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('A', 'Allergy'), ('H', 'Heart Condition'), ('B', 'Blindness'), ('D', 'Deaf')], max_length=64, null=True)),
                ('reaction', models.CharField(max_length=64)),
                ('severity', models.IntegerField(blank=True, choices=[('1', 'Minor'), ('2', 'Low'), ('3', 'Moderate'), ('4', 'Very High'), ('5', 'Severe')], null=True)),
                ('details', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(max_length=32)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhealthdb.Patient')),
            ],
            options={
                'unique_together': {('start', 'title')},
            },
        ),
    ]
