# Generated by Django 2.2.3 on 2019-07-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'staff'},
        ),
    ]
