# Generated by Django 2.2.3 on 2019-07-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientem',
            name='emcontact',
        ),
        migrations.AddField(
            model_name='patientem',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patientem',
            name='name',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientem',
            name='phone1',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientem',
            name='phone2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='patientem',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_pat', to='myhealthdb.Patient'),
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
