# Generated by Django 2.2.3 on 2019-07-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthdb', '0002_auto_20190709_1157'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together={('start', 'title', 'patient')},
        ),
    ]
