# Generated by Django 2.2.3 on 2019-07-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthdb', '0002_auto_20190716_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctor',
            name='note',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='patientdoctor',
            name='inpatient',
            field=models.BooleanField(default=False),
        ),
    ]
