# Generated by Django 2.2.3 on 2019-07-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthdb', '0003_auto_20190716_1825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientdoctor',
            unique_together={('patient', 'doctor')},
        ),
    ]
