# Generated by Django 2.2.3 on 2019-07-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthdb', '0003_auto_20190709_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance_unit',
            field=models.CharField(blank=True, choices=[('m', 'm'), ('Km', 'Km'), ('Mi', 'Mi')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Run', 'Run'), ('Jog', 'Jog'), ('Walk', 'Walk'), ('Cycle', 'Cycle'), ('Swim', 'Swim')], max_length=32),
        ),
        migrations.AlterField(
            model_name='condition',
            name='severity',
            field=models.IntegerField(blank=True, choices=[('Minor', 'Minor'), ('Low', 'Low'), ('Moderate', 'Moderate'), ('Very High', 'Very High'), ('Severe', 'Severe')], null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='type',
            field=models.CharField(blank=True, choices=[('Allergy', 'Allergy'), ('Heart Condition', 'Heart Condition'), ('Blindness', 'Blindness'), ('Deaf', 'Deaf')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Discharge Letter', 'Discharge Letter'), ('Lab Result', 'Lab Result')], max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Surgery', 'Surgery'), ('Consultation', 'Consultation'), ('Imunization', 'Immunization'), ('Emergency', 'Emergency')], max_length=32),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='country',
            field=models.CharField(choices=[('United Kingdom', 'United Kingdom'), ('Ireland', 'Ireland'), ('France', 'France')], max_length=64),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(choices=[('General Practice', 'General Practice'), ('General Hospital', 'General Hospital'), ('Specialized Hospital', 'Specialized Hospital')], max_length=64),
        ),
    ]
