# Generated by Django 2.2.3 on 2019-07-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthdb', '0004_auto_20190716_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myhealthdb.Document'),
        ),
    ]
