# Generated by Django 2.2.3 on 2019-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhealthdb', '0005_auto_20190717_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='default', max_length=32),
            preserve_default=False,
        ),
    ]
